#Assignment_One.py
print("Lets play SS")
name = input("Name")
adjective1 = input("Adjective 1")
adjective2 = input("Adjective 2")
adverb = input("Adverb")
food1 = input("Food 1")
food2 = input("Food 2")
noun = input("Noun")
place = input("Place")
verb = input("Verb")

print(name + " was planning a dream vacation to " + place + ".")
print(name + " was especially looking forward to trying the local ")
print(" cuisine, including " + adjective1 + food1 + " and " + food2 + "\n")
print(name + " will have to practice the language " + adverb + " to ")
print(" make it easier to " + verb + " with people.\n")
print(name + " has a long list of sights to see, including the ")
print(noun + " museum and the " + adjective2 + " park.")
